name: Publish

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  rubygems:
    runs-on: ubuntu-latest
    name: Build and publish

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1
        bundler-cache: true

    - name: Build
      run: gem build

    - name: Publish
      run: gem push *.gem
